version: "3"
services: 
    api:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules
        container_name: MERN-api
        ports: 
            - "8000:8000"
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
        restart: always